# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: client

    steps:
      - uses: actions/checkout@v7
      - name: Set up Node.js 24
        uses: actions/setup-node@v7
        with:
          node-version: '24.x'
      - run: npm ci
      - run: npm run lint
      - run: npm run build --if-present

  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: server

    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4
      - run:
          uv sync --locked
      - run:
          python -c "from main import app"
